require "firebase"
require "json"
require "dotenv"

FIREBASE_DATABASE_URL = ENV["FIREBASE_URI"]

FIREBASE_SERVICE_ACCOUNT_KEY_PATH = File.open(ENV["FIREBASE_SECRET_PATH"]).read

FIREBASE_CLIENT = Firebase::Client.new(FIREBASE_DATABASE_URL, FIREBASE_SERVICE_ACCOUNT_KEY_PATH)
